# Generated by Django 5.1.1 on 2024-09-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('treatment_plan', models.TextField()),
                ('care_status', models.CharField(max_length=100)),
                ('care_notes', models.TextField()),
            ],
        ),
    ]
